name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Cypress tests
        run: |
          yarn cypress:ci

      - name: Archive chromatic assets
        run: |
          yarn archive-storybook

      - name: Run tests
        run: |
          yarn test:ci

      - name: Upload chromatic archives
        uses: actions/upload-artifact@v4
        with:
          name: chromatic-archives
          path: cypress/downloads/chromatic-archives
